version: 16
general:
  license: none
  database:
    url: sqlite://db/TeaData.sqlite
    sqlite:
      locking_mode: EXCLUSIVE
      sync_mode: NORMAL
      journal_mode: WAL
  crash_path: crash_dumps/
  command_prefix: .
  permission_mapping: resources/permission_mapping.txt
log:
  level: 1
  terminal_level: 2
  colored: 0
  vs_size: 0
  path: logs/log_${time}(%Y-%m-%d_%H:%M:%S)_${group}.log
binding:
  voice:
    default_host: "0.0.0.0,::"
    enforce: 0
  web:
    default_host: 0.0.0.0,[::]
  query:
    port: 10101
    host: 0.0.0.0,[::]
  file:
    port: 30303
    host: 0.0.0.0,[::]
query:
  nl_char: "\n"
  max_line_buffer: 1048576
  motd: "TeaSpeak\nWelcome on the TeaSpeak ServerQuery interface.\n"
  enableSSL: 2
  ssl:
    certificate: certs/query_certificate.pem
    privatekey: certs/query_privatekey.pem
voice:
  default_port: 9987
  notifymute: 0
  suppress_myts_warnings: 1
  allow_session_reinitialize: 1
  rsa:
    puzzle_pool_size: 128
  handshake:
    puzzle_level: 1000
    enforce_cookie: 1
    warn_on_permission_editor: 1
  connect_limit: 1024
  client_connect_limit: 1024
  protocol:
    experimental_31: 1
server:
  platform: Linux
  version: "TeaSpeak 1.5.6 [Build: 1622030009]"
  licence: 6
  delete_old_bans: 1
  strict_ut8_mode: 0
  show_invisible_clients: 1
  disable_ip_saving: 0
  default_music_bot: 1
  max_virtual_servers: 16
  limits:
    poke_message_length: 1024
    talk_power_request_message_length: 50
    afk_message_length: 50
  authentication:
    name: 0
  clients:
    teamspeak: 1
    not_allowed_message: ""
    teamspeak_message: ""
    teamspeak_message_type: 0
    teaspeak_message: ""
    teaspeak_message_type: 0
    teaweb: 1
    teaweb_message: ""
    teaweb_message_type: 0
    ignore_max_clone_permissions: 0
web:
  enabled: 1
  ssl: {}
  webrtc:
    port_min: 50000
    port_max: 56000
    stun:
      enabled: 1
      host: stun.l.google.com
      port: 19302
    udp: 1
    tcp: 1
geolocation:
  fallback_country: DE
  force_fallback_country: 0
  mapping:
    file: geoloc/IP2Location.CSV
    type: 0
  vpn:
    file: geoloc/ipcat.csv
    enabled: 0
music:
  enabled: 1
messages:
  voice:
    server_stop: Server stopped
  application:
    stop: Application stopped
    crash: Application crashed
  idle_time: Idle time exceeded
  teamspeak_permission_editor: "\n[b][COLOR=#aa0000]ATTENTION[/COLOR][/b]:\nIt seems like you're trying to edit the TeaSpeak permissions with the TeamSpeak 3 client!\nThis is [b]really[/b] buggy due a bug within the client you're using.\n\nWe recommand to [b]use the [url=https://web.teaspeak.de/]TeaSpeak-Web[/url][/b] client or the [b][url=https://teaspeak.de/]TeaSpeak client[/url][/b].\nYatQA is a good option as well.\n\nTo disable/edit this message please edit the config.yml\nPlease note: Permission bugs, which will be reported wound be accepted."
  mute:
    mute_message: "Hey!\nI muted you!"
    unmute_message: "Hey!\nI unmuted you!"
  kick_invalid:
    hardware_id: Invalid hardware id. Protocol hacked?
    command: Invalid command. Protocol hacked?
    badges: Invalid badges. Protocol hacked?
  vpn:
    kick: "Please disable your VPN! (Provider: ${provider.name})"
  shutdown:
    scheduled: "[b][color=#DA9100]Scheduled shutdown at ${time}(%Y-%m-%d %H:%M:%S)[/color][/b]"
    interval: "[b][color=red]Server instance shutting down in ${interval}[/color][/b]"
    intervals:
      1: 1 second
      2: 2 seconds
      3: 3 seconds
      4: 4 seconds
      5: 5 seconds
      10: 10 seconds
      20: 20 seconds
      30: 30 seconds
      60: 1 minute
      120: 2 minutes
      180: 3 minutes
      300: 5 minutes
      600: 10 minutes
      1200: 20 minutes
      1800: 30 minutes
      3600: 1 hour
      7200: 2 hours
    now: "[b][color=red]Server instance shutting down in now[/color][/b]"
    canceled: "[b][color=green]Scheduled instance shutdown canceled![/color][/b]"
  music:
    song_announcement: Now replaying ${title} (${url}) added by ${invoker}
  timeout:
    connection_reinitialized: Connection lost
    packet_resend_failed: Packet resend failed
threads:
  ticking: 2
  music:
    execute_limit: 5
    execute_per_bot: 1
  command_execute: 4
  network_events: 4
  voice:
    events_per_server: 4
