[Interface]
Address = 10.254.0.1/24
ListenPort = 51820
PrivateKey = eJ+TUYUnLyynoSRt5kP7k7GsKQS0AlyfX6uAjfDQoVA=

[Peer]
## Client 2
AllowedIPs = 10.254.0.2/32
PublicKey = hoa8x24C+R5CeiZrBYutH3wrjTEEK+YNguCYZ97vbUk=